// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(bark_ffiFFI)
import bark_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_bark_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_bark_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBarkFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The main Bark wallet interface for Ark operations
 */
public protocol WalletProtocol: AnyObject, Sendable {
    
    func balance() throws  -> Balance
    
    func bolt11Invoice(amountSats: UInt64) throws  -> LightningInvoice
    
    func maintenance() throws 
    
    func newAddress() throws  -> String
    
    func offboardAll(bitcoinAddress: String) throws  -> OffboardResult
    
    func payLightningAddress(lightningAddress: String, amountSats: UInt64, comment: String?) throws  -> LightningPaymentResult
    
    func payLightningInvoice(invoice: String, amountSats: UInt64?) throws  -> LightningPaymentResult
    
    func properties() throws  -> WalletProperties
    
    func sendArkoorPayment(arkAddress: String, amountSats: UInt64) throws 
    
    func sync() throws 
    
    func tryClaimAllLightningReceives(wait: Bool) throws 
    
    func vtxos() throws  -> [Vtxo]
    
}
/**
 * The main Bark wallet interface for Ark operations
 */
open class Wallet: WalletProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_bark_ffi_fn_clone_wallet(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_bark_ffi_fn_free_wallet(handle, $0) }
    }

    
    /**
     * Create a new Bark wallet
     */
public static func create(mnemonic: String, config: Config, datadir: String, forceRescan: Bool)throws  -> Wallet  {
    return try  FfiConverterTypeWallet_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_constructor_wallet_create(
        FfiConverterString.lower(mnemonic),
        FfiConverterTypeConfig_lower(config),
        FfiConverterString.lower(datadir),
        FfiConverterBool.lower(forceRescan),$0
    )
})
}
    
    /**
     * Open an existing Bark wallet
     */
public static func `open`(mnemonic: String, config: Config, datadir: String)throws  -> Wallet  {
    return try  FfiConverterTypeWallet_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_constructor_wallet_open(
        FfiConverterString.lower(mnemonic),
        FfiConverterTypeConfig_lower(config),
        FfiConverterString.lower(datadir),$0
    )
})
}
    

    
open func balance()throws  -> Balance  {
    return try  FfiConverterTypeBalance_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_balance(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func bolt11Invoice(amountSats: UInt64)throws  -> LightningInvoice  {
    return try  FfiConverterTypeLightningInvoice_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_bolt11_invoice(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(amountSats),$0
    )
})
}
    
open func maintenance()throws   {try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_maintenance(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func newAddress()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_new_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func offboardAll(bitcoinAddress: String)throws  -> OffboardResult  {
    return try  FfiConverterTypeOffboardResult_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_offboard_all(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(bitcoinAddress),$0
    )
})
}
    
open func payLightningAddress(lightningAddress: String, amountSats: UInt64, comment: String?)throws  -> LightningPaymentResult  {
    return try  FfiConverterTypeLightningPaymentResult_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_pay_lightning_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(lightningAddress),
        FfiConverterUInt64.lower(amountSats),
        FfiConverterOptionString.lower(comment),$0
    )
})
}
    
open func payLightningInvoice(invoice: String, amountSats: UInt64?)throws  -> LightningPaymentResult  {
    return try  FfiConverterTypeLightningPaymentResult_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_pay_lightning_invoice(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(invoice),
        FfiConverterOptionUInt64.lower(amountSats),$0
    )
})
}
    
open func properties()throws  -> WalletProperties  {
    return try  FfiConverterTypeWalletProperties_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_properties(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func sendArkoorPayment(arkAddress: String, amountSats: UInt64)throws   {try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_send_arkoor_payment(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(arkAddress),
        FfiConverterUInt64.lower(amountSats),$0
    )
}
}
    
open func sync()throws   {try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_sync(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func tryClaimAllLightningReceives(wait: Bool)throws   {try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_try_claim_all_lightning_receives(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(wait),$0
    )
}
}
    
open func vtxos()throws  -> [Vtxo]  {
    return try  FfiConverterSequenceTypeVtxo.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_vtxos(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWallet: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Wallet

    public static func lift(_ handle: UInt64) throws -> Wallet {
        return Wallet(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Wallet) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Wallet {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Wallet, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lift(_ handle: UInt64) throws -> Wallet {
    return try FfiConverterTypeWallet.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lower(_ value: Wallet) -> UInt64 {
    return FfiConverterTypeWallet.lower(value)
}




/**
 * Detailed balance breakdown of the wallet
 */
public struct Balance: Equatable, Hashable {
    /**
     * Spendable off-chain balance (Ark) in sats
     */
    public var spendableSats: UInt64
    /**
     * Coins locked in a round
     */
    public var pendingInRoundSats: UInt64
    /**
     * Coins being unilaterally exited
     */
    public var pendingExitSats: UInt64
    /**
     * Coins pending as Lightning sends
     */
    public var pendingLightningSendSats: UInt64
    /**
     * Total pending Lightning receives (all invoices)
     */
    public var pendingLightningReceiveTotalSats: UInt64
    /**
     * Claimable pending Lightning receives
     */
    public var pendingLightningReceiveClaimableSats: UInt64
    /**
     * Coins pending board confirmations
     */
    public var pendingBoardSats: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Spendable off-chain balance (Ark) in sats
         */spendableSats: UInt64, 
        /**
         * Coins locked in a round
         */pendingInRoundSats: UInt64, 
        /**
         * Coins being unilaterally exited
         */pendingExitSats: UInt64, 
        /**
         * Coins pending as Lightning sends
         */pendingLightningSendSats: UInt64, 
        /**
         * Total pending Lightning receives (all invoices)
         */pendingLightningReceiveTotalSats: UInt64, 
        /**
         * Claimable pending Lightning receives
         */pendingLightningReceiveClaimableSats: UInt64, 
        /**
         * Coins pending board confirmations
         */pendingBoardSats: UInt64) {
        self.spendableSats = spendableSats
        self.pendingInRoundSats = pendingInRoundSats
        self.pendingExitSats = pendingExitSats
        self.pendingLightningSendSats = pendingLightningSendSats
        self.pendingLightningReceiveTotalSats = pendingLightningReceiveTotalSats
        self.pendingLightningReceiveClaimableSats = pendingLightningReceiveClaimableSats
        self.pendingBoardSats = pendingBoardSats
    }

    
}

#if compiler(>=6)
extension Balance: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBalance: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Balance {
        return
            try Balance(
                spendableSats: FfiConverterUInt64.read(from: &buf), 
                pendingInRoundSats: FfiConverterUInt64.read(from: &buf), 
                pendingExitSats: FfiConverterUInt64.read(from: &buf), 
                pendingLightningSendSats: FfiConverterUInt64.read(from: &buf), 
                pendingLightningReceiveTotalSats: FfiConverterUInt64.read(from: &buf), 
                pendingLightningReceiveClaimableSats: FfiConverterUInt64.read(from: &buf), 
                pendingBoardSats: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Balance, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.spendableSats, into: &buf)
        FfiConverterUInt64.write(value.pendingInRoundSats, into: &buf)
        FfiConverterUInt64.write(value.pendingExitSats, into: &buf)
        FfiConverterUInt64.write(value.pendingLightningSendSats, into: &buf)
        FfiConverterUInt64.write(value.pendingLightningReceiveTotalSats, into: &buf)
        FfiConverterUInt64.write(value.pendingLightningReceiveClaimableSats, into: &buf)
        FfiConverterUInt64.write(value.pendingBoardSats, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalance_lift(_ buf: RustBuffer) throws -> Balance {
    return try FfiConverterTypeBalance.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalance_lower(_ value: Balance) -> RustBuffer {
    return FfiConverterTypeBalance.lower(value)
}


/**
 * Configuration for creating/opening a Bark wallet
 */
public struct Config: Equatable, Hashable {
    public var serverAddress: String
    public var esploraAddress: String?
    public var network: Network
    public var vtxoRefreshExpiryThreshold: UInt32?
    public var vtxoExitMargin: UInt16?
    public var htlcRecvClaimDelta: UInt16?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(serverAddress: String, esploraAddress: String?, network: Network, vtxoRefreshExpiryThreshold: UInt32?, vtxoExitMargin: UInt16?, htlcRecvClaimDelta: UInt16?) {
        self.serverAddress = serverAddress
        self.esploraAddress = esploraAddress
        self.network = network
        self.vtxoRefreshExpiryThreshold = vtxoRefreshExpiryThreshold
        self.vtxoExitMargin = vtxoExitMargin
        self.htlcRecvClaimDelta = htlcRecvClaimDelta
    }

    
}

#if compiler(>=6)
extension Config: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Config {
        return
            try Config(
                serverAddress: FfiConverterString.read(from: &buf), 
                esploraAddress: FfiConverterOptionString.read(from: &buf), 
                network: FfiConverterTypeNetwork.read(from: &buf), 
                vtxoRefreshExpiryThreshold: FfiConverterOptionUInt32.read(from: &buf), 
                vtxoExitMargin: FfiConverterOptionUInt16.read(from: &buf), 
                htlcRecvClaimDelta: FfiConverterOptionUInt16.read(from: &buf)
        )
    }

    public static func write(_ value: Config, into buf: inout [UInt8]) {
        FfiConverterString.write(value.serverAddress, into: &buf)
        FfiConverterOptionString.write(value.esploraAddress, into: &buf)
        FfiConverterTypeNetwork.write(value.network, into: &buf)
        FfiConverterOptionUInt32.write(value.vtxoRefreshExpiryThreshold, into: &buf)
        FfiConverterOptionUInt16.write(value.vtxoExitMargin, into: &buf)
        FfiConverterOptionUInt16.write(value.htlcRecvClaimDelta, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfig_lift(_ buf: RustBuffer) throws -> Config {
    return try FfiConverterTypeConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfig_lower(_ value: Config) -> RustBuffer {
    return FfiConverterTypeConfig.lower(value)
}


/**
 * Result of creating a BOLT11 invoice
 */
public struct LightningInvoice: Equatable, Hashable {
    /**
     * The BOLT11 invoice string
     */
    public var invoice: String
    /**
     * Amount in sats
     */
    public var amountSats: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The BOLT11 invoice string
         */invoice: String, 
        /**
         * Amount in sats
         */amountSats: UInt64) {
        self.invoice = invoice
        self.amountSats = amountSats
    }

    
}

#if compiler(>=6)
extension LightningInvoice: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightningInvoice: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightningInvoice {
        return
            try LightningInvoice(
                invoice: FfiConverterString.read(from: &buf), 
                amountSats: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: LightningInvoice, into buf: inout [UInt8]) {
        FfiConverterString.write(value.invoice, into: &buf)
        FfiConverterUInt64.write(value.amountSats, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningInvoice_lift(_ buf: RustBuffer) throws -> LightningInvoice {
    return try FfiConverterTypeLightningInvoice.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningInvoice_lower(_ value: LightningInvoice) -> RustBuffer {
    return FfiConverterTypeLightningInvoice.lower(value)
}


/**
 * Result of a successful lightning payment
 */
public struct LightningPaymentResult: Equatable, Hashable {
    /**
     * The invoice that was paid
     */
    public var invoice: String
    /**
     * Payment preimage as hex string
     */
    public var preimage: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The invoice that was paid
         */invoice: String, 
        /**
         * Payment preimage as hex string
         */preimage: String) {
        self.invoice = invoice
        self.preimage = preimage
    }

    
}

#if compiler(>=6)
extension LightningPaymentResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightningPaymentResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightningPaymentResult {
        return
            try LightningPaymentResult(
                invoice: FfiConverterString.read(from: &buf), 
                preimage: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: LightningPaymentResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.invoice, into: &buf)
        FfiConverterString.write(value.preimage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningPaymentResult_lift(_ buf: RustBuffer) throws -> LightningPaymentResult {
    return try FfiConverterTypeLightningPaymentResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningPaymentResult_lower(_ value: LightningPaymentResult) -> RustBuffer {
    return FfiConverterTypeLightningPaymentResult.lower(value)
}


/**
 * Result of an offboard operation
 */
public struct OffboardResult: Equatable, Hashable {
    /**
     * The round ID
     */
    public var roundId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The round ID
         */roundId: String) {
        self.roundId = roundId
    }

    
}

#if compiler(>=6)
extension OffboardResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOffboardResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OffboardResult {
        return
            try OffboardResult(
                roundId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: OffboardResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.roundId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOffboardResult_lift(_ buf: RustBuffer) throws -> OffboardResult {
    return try FfiConverterTypeOffboardResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOffboardResult_lower(_ value: OffboardResult) -> RustBuffer {
    return FfiConverterTypeOffboardResult.lower(value)
}


/**
 * Simplified view of a VTXO
 */
public struct Vtxo: Equatable, Hashable {
    /**
     * VTXO id like "686...9aa:0"
     */
    public var id: String
    /**
     * Amount in sats
     */
    public var amountSats: UInt64
    /**
     * Expiry height (0 if unknown)
     */
    public var expiryHeight: UInt32
    /**
     * Type of VTXO (e.g., "board", "round", "arkoor")
     */
    public var kind: String
    /**
     * State of VTXO (e.g., "spendable", "spent", "locked")
     */
    public var state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * VTXO id like "686...9aa:0"
         */id: String, 
        /**
         * Amount in sats
         */amountSats: UInt64, 
        /**
         * Expiry height (0 if unknown)
         */expiryHeight: UInt32, 
        /**
         * Type of VTXO (e.g., "board", "round", "arkoor")
         */kind: String, 
        /**
         * State of VTXO (e.g., "spendable", "spent", "locked")
         */state: String) {
        self.id = id
        self.amountSats = amountSats
        self.expiryHeight = expiryHeight
        self.kind = kind
        self.state = state
    }

    
}

#if compiler(>=6)
extension Vtxo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVtxo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Vtxo {
        return
            try Vtxo(
                id: FfiConverterString.read(from: &buf), 
                amountSats: FfiConverterUInt64.read(from: &buf), 
                expiryHeight: FfiConverterUInt32.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Vtxo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterUInt64.write(value.amountSats, into: &buf)
        FfiConverterUInt32.write(value.expiryHeight, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVtxo_lift(_ buf: RustBuffer) throws -> Vtxo {
    return try FfiConverterTypeVtxo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVtxo_lower(_ value: Vtxo) -> RustBuffer {
    return FfiConverterTypeVtxo.lower(value)
}


/**
 * Read-only properties of the wallet
 */
public struct WalletProperties: Equatable, Hashable {
    public var network: Network
    public var fingerprint: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(network: Network, fingerprint: String) {
        self.network = network
        self.fingerprint = fingerprint
    }

    
}

#if compiler(>=6)
extension WalletProperties: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletProperties: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletProperties {
        return
            try WalletProperties(
                network: FfiConverterTypeNetwork.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WalletProperties, into buf: inout [UInt8]) {
        FfiConverterTypeNetwork.write(value.network, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletProperties_lift(_ buf: RustBuffer) throws -> WalletProperties {
    return try FfiConverterTypeWalletProperties.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletProperties_lower(_ value: WalletProperties) -> RustBuffer {
    return FfiConverterTypeWalletProperties.lower(value)
}


/**
 * Error types that can occur when using the Bark wallet
 */
public enum BarkError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Network(message: String
    )
    case Database(message: String
    )
    case InvalidMnemonic(message: String
    )
    case InvalidAddress(message: String
    )
    case InvalidInvoice(message: String
    )
    case InsufficientFunds(message: String
    )
    case NotFound(message: String
    )
    case ServerConnection(message: String
    )
    case Internal(message: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension BarkError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBarkError: FfiConverterRustBuffer {
    typealias SwiftType = BarkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BarkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Network(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Database(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidMnemonic(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidAddress(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .InvalidInvoice(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .InsufficientFunds(
            message: try FfiConverterString.read(from: &buf)
            )
        case 7: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
            )
        case 8: return .ServerConnection(
            message: try FfiConverterString.read(from: &buf)
            )
        case 9: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BarkError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Network(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Database(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidMnemonic(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidAddress(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidInvoice(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InsufficientFunds(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .NotFound(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ServerConnection(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBarkError_lift(_ buf: RustBuffer) throws -> BarkError {
    return try FfiConverterTypeBarkError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBarkError_lower(_ value: BarkError) -> RustBuffer {
    return FfiConverterTypeBarkError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Bitcoin network types
 */

public enum Network: Equatable, Hashable {
    
    case bitcoin
    case testnet
    case signet
    case regtest



}

#if compiler(>=6)
extension Network: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNetwork: FfiConverterRustBuffer {
    typealias SwiftType = Network

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Network {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bitcoin
        
        case 2: return .testnet
        
        case 3: return .signet
        
        case 4: return .regtest
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Network, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bitcoin:
            writeInt(&buf, Int32(1))
        
        
        case .testnet:
            writeInt(&buf, Int32(2))
        
        
        case .signet:
            writeInt(&buf, Int32(3))
        
        
        case .regtest:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetwork_lift(_ buf: RustBuffer) throws -> Network {
    return try FfiConverterTypeNetwork.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetwork_lower(_ value: Network) -> RustBuffer {
    return FfiConverterTypeNetwork.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeVtxo: FfiConverterRustBuffer {
    typealias SwiftType = [Vtxo]

    public static func write(_ value: [Vtxo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeVtxo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Vtxo] {
        let len: Int32 = try readInt(&buf)
        var seq = [Vtxo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeVtxo.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_bark_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_balance() != 11221) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_bolt11_invoice() != 64551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_maintenance() != 9626) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_new_address() != 25174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_offboard_all() != 61123) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_pay_lightning_address() != 8340) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_pay_lightning_invoice() != 3587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_properties() != 34715) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_send_arkoor_payment() != 24856) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_sync() != 3312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_try_claim_all_lightning_receives() != 53132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_vtxos() != 16778) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_constructor_wallet_create() != 28953) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_constructor_wallet_open() != 34910) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBarkFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all