//
//  AddressHistoryView_iOS.swift
//  Arké
//
//  Created by Christoph on 01/12/26.
//

import SwiftUI
import SwiftData
import ArkeUI

struct AddressHistoryView_iOS: View {
    @Query(
        filter: #Predicate<PersistentAddress> { $0.isActive },
        sort: \PersistentAddress.generatedAt,
        order: .reverse
    )
    private var allAddresses: [PersistentAddress]
    
    @State private var copiedAddress: String?
    
    // Computed properties to filter by type
    private var arkAddresses: [PersistentAddress] {
        allAddresses.filter { $0.addressType == "ark" }
    }
    
    private var bitcoinAddresses: [PersistentAddress] {
        allAddresses.filter { $0.addressType == "onchain" }
    }
    
    var body: some View {
        VStack(spacing: 0) {
            Text("There are all the addresses generated by your wallet. Payments (Ark) addresses can be re-used, while savings (Bitcoin) addresses should be only used once in order to preserve your privacy.")
                .font(.body)
                .foregroundColor(.secondary)
                .padding(.horizontal, 16)
                .padding(.vertical, 12)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color(uiColor: .systemGroupedBackground))
            
            List {
                // Ark Addresses Section
                if !arkAddresses.isEmpty {
                    Section {
                        ForEach(arkAddresses) { address in
                            AddressHistoryRowView(
                                address: address,
                                copiedAddress: $copiedAddress
                            )
                            .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 16))
                        }
                    } header: {
                        Text("Payments Addresses (Ark)")
                    }
                    .padding(.vertical, 8)
                }
                
                // Bitcoin Addresses Section
                if !bitcoinAddresses.isEmpty {
                    Section {
                        ForEach(bitcoinAddresses) { address in
                            AddressHistoryRowView(
                                address: address,
                                copiedAddress: $copiedAddress
                            )
                            .listRowInsets(EdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 16))
                        }
                    } header: {
                        Text("Savings Addresses (Bitcoin)")
                    }
                    .padding(.vertical, 8)
                }
                
                // Empty State
                if allAddresses.isEmpty {
                    Section {
                        VStack(spacing: 12) {
                            Image(systemName: "tray")
                                .font(.largeTitle)
                                .foregroundColor(.secondary)
                            Text("No addresses yet")
                                .font(.headline)
                                .foregroundColor(.secondary)
                            Text("Addresses will appear here as they are generated")
                                .font(.subheadline)
                                .foregroundColor(.secondary)
                                .multilineTextAlignment(.center)
                        }
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 32)
                    }
                }
            }
        }
        .navigationTitle("Address History")
        .navigationBarTitleDisplayMode(.large)
    }
}

// MARK: - Address Row View

struct AddressHistoryRowView: View {
    let address: PersistentAddress
    @Binding var copiedAddress: String?
    @State private var isExpanded = false
    @State private var showingCopied = false
    
    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            VStack(alignment: .leading, spacing: 4) {
                // Address string with expandable view
                ExpandableAddressView(address: address.address, isExpanded: $isExpanded, animated: false)
                
                // Additional info row
                HStack(spacing: 4) {
                    Text(address.generatedAt, style: .relative)
                        .font(.caption)
                    Text("ago")
                        .font(.caption)
                    
                    if let index = address.derivationIndex {
                        Text("•")
                            .foregroundColor(.secondary)
                        Text("Address #\(index)")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                }
                .foregroundColor(.secondary)
            }
            
            Spacer()
            
            // Dedicated copy button
            Button {
                copyAddress()
            } label: {
                Image(systemName: showingCopied ? "checkmark" : "doc.on.doc.fill")
                    .foregroundStyle(showingCopied ? .green : .arkeGold)
                    .frame(width: 16, height: 16)
                    .padding(.horizontal, 4)
                    .padding(.vertical, 6)
                    .contentTransition(.symbolEffect(.replace))
                    .scaleEffect(showingCopied ? 1.1 : 1.0)
            }
            .buttonStyle(.bordered)
            .tint(showingCopied ? .green : .arkeGold)
        }
        .frame(maxWidth: .infinity, alignment: .top)
        .sensoryFeedback(.success, trigger: showingCopied)
    }
    
    // MARK: - Actions
    
    private func copyAddress() {
        UIPasteboard.general.string = address.address
        
        // Show copied feedback
        withAnimation(.spring(response: 0.3, dampingFraction: 0.6)) {
            showingCopied = true
            copiedAddress = address.address
        }
        
        // Clear feedback after delay
        Task {
            try? await Task.sleep(nanoseconds: 1_500_000_000)
            withAnimation {
                showingCopied = false
                if copiedAddress == address.address {
                    copiedAddress = nil
                }
            }
        }
    }
}

// MARK: - Previews

#Preview {
    NavigationStack {
        AddressHistoryView_iOS()
    }
    .modelContainer(for: [PersistentAddress.self], inMemory: true)
}
