//
//  AddressHistoryView_iOS.swift
//  Arké
//
//  Created by Christoph on 01/12/26.
//

import SwiftUI
import SwiftData

struct AddressHistoryView_iOS: View {
    @Query(
        filter: #Predicate<PersistentAddress> { $0.isActive },
        sort: \PersistentAddress.generatedAt,
        order: .reverse
    )
    private var allAddresses: [PersistentAddress]
    
    @State private var copiedAddress: String?
    
    // Computed properties to filter by type
    private var arkAddresses: [PersistentAddress] {
        allAddresses.filter { $0.addressType == "ark" }
    }
    
    private var bitcoinAddresses: [PersistentAddress] {
        allAddresses.filter { $0.addressType == "onchain" }
    }
    
    var body: some View {
        List {
            Text("There are all the addresses generated by your wallet. Ark addresses can be re-used, while bitcoin addresses should be only used once in order to preserve your privacy.")
                .font(.body)
                .foregroundColor(.secondary)
                .listRowInsets(EdgeInsets())
                .listRowBackground(Color.clear)
                .listRowSeparator(.hidden)
            
            // Ark Addresses Section
            if !arkAddresses.isEmpty {
                Section {
                    ForEach(arkAddresses) { address in
                        AddressRowView(
                            address: address,
                            copiedAddress: $copiedAddress
                        )
                    }
                } header: {
                    Text("Ark Addresses")
                }
            }
            
            // Bitcoin Addresses Section
            if !bitcoinAddresses.isEmpty {
                Section {
                    ForEach(bitcoinAddresses) { address in
                        AddressRowView(
                            address: address,
                            copiedAddress: $copiedAddress
                        )
                    }
                } header: {
                    Text("Bitcoin Addresses")
                }
            }
            
            // Empty State
            if allAddresses.isEmpty {
                Section {
                    VStack(spacing: 12) {
                        Image(systemName: "tray")
                            .font(.largeTitle)
                            .foregroundColor(.secondary)
                        Text("No addresses yet")
                            .font(.headline)
                            .foregroundColor(.secondary)
                        Text("Addresses will appear here as they are generated")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                            .multilineTextAlignment(.center)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 32)
                }
            }
        }
        .navigationTitle("Address History")
        .navigationBarTitleDisplayMode(.large)
    }
}

// MARK: - Address Row View

struct AddressRowView: View {
    let address: PersistentAddress
    @Binding var copiedAddress: String?
    
    var body: some View {
        Button {
            copyAddress()
        } label: {
            HStack(spacing: 12) {
                // Icon based on address type
                /*
                Image(systemName: iconName)
                    .font(.title3)
                    .foregroundColor(iconColor)
                    .frame(width: 28)
                */
                
                VStack(alignment: .leading, spacing: 4) {
                    // Type and status row
                    /*
                    HStack(spacing: 8) {
                        Text(address.type.displayName)
                            .font(.subheadline)
                            .fontWeight(.medium)
                        
                        if let index = address.derivationIndex {
                            Text("•")
                                .foregroundColor(.secondary)
                            Text("Address #\(index)")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                        
                        Spacer()
                        
                        // Usage badge
                        if address.isUsed {
                            HStack(spacing: 4) {
                                Image(systemName: "checkmark.circle.fill")
                                    .font(.caption2)
                                Text("Used")
                                    .font(.caption)
                            }
                            .foregroundColor(.green)
                        } else {
                            Text("Unused")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }
                    */
                    
                    // Address string
                    Text(address.address)
                        .font(.system(.body, design: .monospaced))
                        .lineLimit(1)
                        .truncationMode(.middle)
                        .foregroundColor(.primary)
                    
                    // Additional info row
                    HStack(spacing: 4) {
                        if address.isUsed {
                            Text("\(address.receivedTransactionCount) tx")
                                .font(.caption)
                        } else {
                            Text("Unused")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                        
                        Text("•")
                            .font(.caption)
                            
                        Text(address.generatedAt, style: .relative)
                            .font(.caption)
                        Text("ago")
                            .font(.caption)
                        
                        if let index = address.derivationIndex {
                            Text("•")
                                .foregroundColor(.secondary)
                            Text("Address #\(index)")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                        /*
                        Text("•")
                            .foregroundColor(.secondary)
                        
                        // Usage badge
                        if address.isUsed {
                            HStack(spacing: 4) {
                                Image(systemName: "checkmark.circle.fill")
                                    .font(.caption2)
                                Text("Used")
                                    .font(.caption)
                            }
                            .foregroundColor(.green)
                        } else {
                            Text("Unused")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                        */
                    }
                    .foregroundColor(.secondary)
                }
                
                // Copy indicator or icon
                if copiedAddress == address.address {
                    Image(systemName: "checkmark")
                        .font(.caption)
                        .foregroundColor(.green)
                        .transition(.scale.combined(with: .opacity))
                } else {
                    Image(systemName: "doc.on.doc")
                        .font(.caption)
                        .foregroundColor(.blue)
                }
            }
            .padding(.vertical, 4)
        }
        .buttonStyle(.plain)
        .sensoryFeedback(.success, trigger: copiedAddress)
    }
    
    // MARK: - Computed Properties
    
    private var iconName: String {
        switch address.type {
        case .ark:
            return "bolt.fill"
        case .onchain:
            return "bitcoinsign.circle.fill"
        }
    }
    
    private var iconColor: Color {
        switch address.type {
        case .ark:
            return .purple
        case .onchain:
            return .orange
        }
    }
    
    // MARK: - Actions
    
    private func copyAddress() {
        UIPasteboard.general.string = address.address
        
        // Show copied feedback
        withAnimation(.spring(duration: 0.3)) {
            copiedAddress = address.address
        }
        
        // Clear feedback after delay
        Task {
            try? await Task.sleep(for: .seconds(2))
            withAnimation(.spring(duration: 0.3)) {
                if copiedAddress == address.address {
                    copiedAddress = nil
                }
            }
        }
    }
}

// MARK: - Previews

#Preview {
    NavigationStack {
        AddressHistoryView_iOS()
    }
    .modelContainer(for: [PersistentAddress.self], inMemory: true)
}
